server:
  port: 8080


spring:
  application:
    name: serviceA

eureka:
  instance:
    instance-id: serviceA
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/