spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    protocol: smtp
    username: flyingzd@qq.com
    password: pntpigudfbcicbeb
  smtp:
    auth: true
    starttls:
      enable: true
      required: true

alert:
  mail:
    from: ${spring.mail.username}
    to: flyingzd@qq.com
    subject: IP变动

ip:
  obtain:
    error:
      max_time: 1000
    obtainer: urlIp42IpObtainer

logging:
  file:
    name: /logs/ip-alert.log

task:
  initDelay: 5000
  delay: 1200000